language: nix

git:
  submodules: false

matrix:
  include:
    - os: linux
      script:
        - nix-build
        - ./scripts/run-tests
    - os: linux
      dist: trusty
      script:
        - nix-build
        - ./scripts/run-tests
    - os: osx
      osx_image: xcode7.3
      script:
        - nix-build
        - ./scripts/run-tests
