language: nix

git:
  submodules: false

matrix:
  include:
    - os: linux
      script:
        - export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
        - nix-build
        - ./scripts/run-tests
    - os: linux
      dist: trusty
      script:
        - export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
        - nix-build
        - ./scripts/run-tests
    - os: osx
      osx_image: xcode7.3
      script:
        - export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
        - nix-build
        - ./scripts/run-tests
